name: dart_license_checker
description: Shows you which licenses your dependencies have.
version: 1.1.1
homepage: https://github.com/redsolver/dart_license_checker

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path: ^1.7.0
  tint: ^2.0.0
  pana: ^0.15.4
  pubspec_parse: ^0.1.8
  barbecue: ^0.2.0

dev_dependencies:
  pedantic: ^1.9.0

executables:
  dart_license_checker: dart_license_checker